create extension if not exists vector with schema extensions; 

create table pages (
  id bigint generated by default as identity primary key,
  name text not null,
  path text not null
);

create table page_sections (
  id bigint generated by default as identity primary key,
  page_id bigint not null references pages on delete cascade,
  content text not null,
  embedding vector(1024)
)