create extension if not exists vector with schema extensions; 

create table users (
  id text primary key,
  username text not null,
  email text not null unique
);

create table pages (
  id bigint generated by default as identity primary key,
  name text not null,
  path text not null,
  user_id text not null references users on delete cascade,
  created_at timestamptz default now()
);

create table page_sections (
  id bigint generated by default as identity primary key,
  page_id bigint not null references pages on delete cascade,
  content text not null,
  embedding extensions.vector(1024)
)