-- ============================================================
-- 1. Create user_pages junction table
-- ============================================================
create table user_pages (
  id bigint generated by default as identity primary key,
  user_id text not null references users on delete cascade,
  page_id bigint not null references pages on delete cascade,
  is_read boolean not null default false,
  note text,
  note_updated_at timestamptz,
  created_at timestamptz default now(),
  unique (user_id, page_id)
);

-- ============================================================
-- 2. Migrate existing data into junction table
-- ============================================================
insert into user_pages (user_id, page_id, is_read)
select user_id, id, coalesce(is_read, false) from pages;

-- ============================================================
-- 3. Drop columns from pages that moved to junction
-- ============================================================
alter table pages drop column user_id;
alter table pages drop column is_read;

-- ============================================================
-- 4. Update add_page RPC — remove user_id_input
-- ============================================================
drop function if exists add_page(text, text, text, page_section_data[], page_type, text, text);

create or replace function add_page (
  name_input text,
  page_content text,
  page_section_data_input page_section_data[],
  type_input page_type,
  path_input text,
  checksum_input text
)
returns bigint as
$$
declare
  section_data page_section_data;
  page_id bigint;
begin
  -- Assert that path is provided for website pages
  IF type_input = 'website' AND path_input IS NULL THEN
    RAISE EXCEPTION 'Path is required for website pages';
  END IF;

  -- Insert page
  insert into pages (name, path, type, content, checksum)
  values (name_input, path_input, type_input, page_content, checksum_input)
  returning id into page_id;

  -- Insert page sections
  foreach section_data in array page_section_data_input
  loop
    insert into page_sections (page_id, content, embedding)
    values (page_id, section_data.content, section_data.embedding);
  end loop;

  return page_id;
end;
$$ language plpgsql;

-- ============================================================
-- 5. Update get_matched_pages — join through user_pages
-- ============================================================
drop function if exists get_matched_pages(text, extensions.vector(1024), int, page_type);

create or replace function get_matched_pages (
  user_id_input text,
  query_embedding extensions.vector(1024),
  match_limit int,
  type_input page_type DEFAULT NULL
)
returns table (id bigint, name text, path text, type page_type, max_similarity float, created_at timestamptz, is_read boolean, note text)
language plpgsql
as $$
#variable_conflict use_column
begin
  return query
  select
    pages.id,
    pages.name,
    pages.path,
    pages.type,
    MAX(1 - (page_sections.embedding <=> query_embedding)) AS max_similarity,
    pages.created_at,
    user_pages.is_read,
    user_pages.note
  from pages
  inner join user_pages on user_pages.page_id = pages.id
  inner join page_sections on page_sections.page_id = pages.id
  where user_pages.user_id = user_id_input
    and (type_input is null or pages.type = type_input)
  group by pages.id, pages.name, pages.path, pages.type, pages.created_at, user_pages.is_read, user_pages.note
  order by max_similarity desc
  limit match_limit;
end
$$;

-- ============================================================
-- 6. Update get_matched_page_sections — join through user_pages
-- ============================================================
drop function if exists get_matched_page_sections(text, extensions.vector(1024), int, page_type);

create or replace function get_matched_page_sections (
  user_id_input text,
  query_embedding extensions.vector(1024),
  match_limit int,
  type_input page_type DEFAULT NULL
)
returns table (page_id bigint, section_id bigint, section_content text, similarity float)
language plpgsql
as $$
begin
  return query
  select
    pages.id,
    page_sections.id,
    page_sections.content,
    1 - (page_sections.embedding <=> query_embedding) as similarity
  from pages
  inner join user_pages on user_pages.page_id = pages.id
  inner join page_sections on page_sections.page_id = pages.id
  where user_pages.user_id = user_id_input
    and (type_input is null or pages.type = type_input)
  order by similarity desc
  limit match_limit;
end
$$;

-- ============================================================
-- 7. Enable Realtime on user_pages
-- ============================================================
alter publication supabase_realtime add table user_pages;
